### ISSUE TITLE
dao accounts

### ISSUE THREAD

**Issue by aswever** [envoylabs/howl-ui#39]
- if you have voting power in a dao, and it has a dens alias, you can select it as an account
- instead of directly sending howls, you can propose howls, which will create a dao proposal with a post howl wasm message
- for dao accounts there can be a view of pending howls, which you can vote on (within our UI)
  - we'll just have to fetch all proposals and filter by name
- once the howl proposal has passed, there will be a send howl button which will execute the contract
- dao accounts could have some visible marker

**Comment by the-frey** [comment]
this would be sick
